#!/usr/bin/ruby

begin
  require 'commandline'
  require 'polyglot'
  require 'treetop'
rescue LoadError
  require 'rubygems'
  retry
end

require 'rubyex'

class App < CommandLine::Application
  def initialize
    version		"0.1"
    author		"Arlen Christian Mart Cuss <celtic@sairyx.org>"
    copyright		"Copyright (c) 2008, Arlen Cuss"
    synopsis		"[-Vh] [--in in_file] [--out out_file]"
    short_description	"Translates Ruby source code into rubyex bytecode"
    # long_description

    option 	:version, :names => %w(--version -V)
    option 	:help

    option :names => "--in", :opt_found => get_args,
      :opt_description => "Input file", :arg_description => "input_file"
    option :names => "--out", :opt_found => get_args,
      :opt_description => "Output file", :arg_description => "output_file"
  end

  def main
    in_file, out_file = opt.in, opt.out
    
    if in_file.nil? and out_file.nil?
      puts "You need to specify at least an input file or an output file."
      exit 1
    end
    
    # Now we have to process Ruby. Fuck.
    parser = RubyexParser.new
    syntax_tree = parser.parse(File.read(in_file))
    syntax_tree.display
    p parser.terminal_failures
  end
end

class Treetop::Runtime::SyntaxNode
  def display(level=0)
    puts inspect
  end
end
